# This workflow builds and installs the sand command, installs the apple/contaner command,
# then runs some basic sand subcommands to verify that basic features work as expected.

name: Smoke Test
on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Working directory for the workflow"
        required: false
        type: string
        # default: "${{ vars.WORKING_DIR || '.' }}"
  push:
    branches-ignore:
      - "queue-main-*"
      - "queue-dev-*"
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "${{ inputs.working-directory || '.'}}/go.mod"
          cache: true

      - name: Cache Go 1.25.1
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go1.25.1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go1.25.1-

      # - name: Download apple/container 0.7.1 installer
      #   run: |
      #     curl -L "https://github.com/apple/container/releases/download/0.7.1/container-installer-signed.pkg" -o container-installer-signed.pkg

      # - name: Install .pkg file
      #   run: |
      #     sudo installer -pkg container-installer-signed.pkg -target /

      # - name: check for installer files
      #   run: pkgutil --only-files --files com.apple.container-installer

      - name: Verify "container" command installation
        run: |
          ls /usr/local/bin/container # Verify the app is present

      - name: start container system
        run: yes | container system start

      - name: Install sand
        run: go install github.com/banksean/sand/cmd/sand

      - name: sand version
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand version

      - name: sand daemon --log-file=/tmp/sand/log
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand daemon # should print that daemon is running

      - name: sand new and exit
        working-directory: ${{ inputs.working-directory || '.'}}
        run: echo "exit" | sand new 

      - name: sand ls
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand ls

      - name: sand rm
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand rm -a

      - name: sand daemon stop
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand daemon stop

      - name: Print cli logs on failure
        if: failure()
        run: cat /tmp/sand/log

      - name: Print daemon logs on failure
        if: failure()
        run: cat /tmp/sand/log.daemon
