# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Smoke Test
on:
  workflow_call:
    inputs:
      ref:
        description: "The git ref to checkout"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Working directory for the workflow"
        required: false
        type: string
        # default: "${{ vars.WORKING_DIR || '.' }}"
  push:
    branches-ignore:
      - "queue-main-*"
      - "queue-dev-*"
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: "${{ inputs.working-directory || '.'}}/go.mod"
          cache: true

      - name: Cache Go 1.25.1
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-go1.25.1-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go1.25.1-

      # - name: Download apple/container 0.6.0 installer
      #   run: |
      #     curl -L "https://github.com/apple/container/releases/download/0.6.0/container-0.6.0-installer-signed.pkg" -o container-0.6.0-installer-signed.pkg

      # - name: Install .pkg file
      #   run: |
      #     sudo installer -pkg container-0.6.0-installer-signed.pkg -target /

      # - name: check for installer files
      #   run: pkgutil --only-files --files com.apple.container-installer

      # - name: Verify "container" command installation
      #   run: |
      #     ls /usr/local/bin/container # Verify the app is present

      # - name: debug container status
      #   run: /bin/launchctl list

      - name: brew install container
        run: brew install --cask container

      - name: container system logs
        run: container system logs --last 1d

      # - name: container status
      #   run: sudo container --debug system status

      - name: start container system
        run: sudo container --debug system start

      - name: Install sand
        run: go install github.com/banksean/sand/cmd/sand

      - name: sand version
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand version

      - name: sand doc
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand doc

      - name: sand daemon pre-ls
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand daemon # should print that daemon is not running

      - name: sand ls
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand ls

      - name: sand daemon post-ls
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand daemon # should print that daemon is running

      # - name: sand new
      #   working-directory: ${{ inputs.working-directory || '.'}}
      #   run: sand new -b test-sandbox

      # - name: sand rm
      #   working-directory: ${{ inputs.working-directory || '.'}}
      #   run: sand rm -a

      - name: sand daemon stop
        working-directory: ${{ inputs.working-directory || '.'}}
        run: sand daemon stop
